services:
  - type: pserv
    name: suitecrm-db
    runtime: docker
    plan: starter
    image:
      url: docker.io/bitnami/mariadb:latest
    envVars:
      - key: MARIADB_ROOT_PASSWORD
        generateValue: true
      - key: MARIADB_DATABASE
        value: suitecrm_db
      - key: MARIADB_USER
        value: suitecrm_user
      - key: MARIADB_PASSWORD
        generateValue: true
      - key: ALLOW_EMPTY_PASSWORD
        value: "yes"
    disk:
      name: suitecrm-db-data
      mountPath: /bitnami/mariadb
      sizeGB: 10

  - type: web
    name: suitecrm
    runtime: docker
    plan: starter
    image:
      url: docker.io/bitnami/suitecrm:latest
    envVars:
      - key: SUITECRM_DATABASE_HOST
        fromService:
          type: pserv
          name: suitecrm-db
          property: host
      - key: SUITECRM_DATABASE_PORT_NUMBER
        value: "3306"
      - key: SUITECRM_DATABASE_NAME
        fromService:
          type: pserv
          name: suitecrm-db
          envVarKey: MARIADB_DATABASE
      - key: SUITECRM_DATABASE_USER
        fromService:
          type: pserv
          name: suitecrm-db
          envVarKey: MARIADB_USER
      - key: SUITECRM_DATABASE_PASSWORD
        fromService:
          type: pserv
          name: suitecrm-db
          envVarKey: MARIADB_PASSWORD
      - key: SUITECRM_USERNAME
        value: admin
      - key: SUITECRM_PASSWORD
        generateValue: true
      - key: SUITECRM_EMAIL
        value: admin@example.com
      - key: ALLOW_EMPTY_PASSWORD
        value: "yes"
    disk:
      name: suitecrm-data
      mountPath: /bitnami/suitecrm
      sizeGB: 10
